# permissions for end users to view functionbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: functionbuild-viewer-role
rules:
- apiGroups:
  - openfunction.io
  resources:
  - functionbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfunction.io
  resources:
  - functionbuilds/status
  verbs:
  - get
