# permissions for end users to view servings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serving-viewer-role
rules:
- apiGroups:
  - openfunction.io
  resources:
  - servings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openfunction.io
  resources:
  - servings/status
  verbs:
  - get
