- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/openFuncAsync/properties/dapr/properties/components/items/properties/metadata/items/properties/value/type
  value: ""